
import database.dbconnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aizarrahima
 */
public class NilaiMahasiswa extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;

    dbconnection koneksi;

    String nama, grade, keterangan;
    int nim;
    double nilai_tugas, nilai_uts, nilai_uas, nilai_quiz, rerata;

    public NilaiMahasiswa() {
        initComponents();

        koneksi = new dbconnection();
        conn = koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInputData = new javax.swing.JPanel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabelNIM = new javax.swing.JLabel();
        jTextFieldNIM = new javax.swing.JTextField();
        jLabelNilaiTugas = new javax.swing.JLabel();
        jTextFieldNilaiTugas = new javax.swing.JTextField();
        jLabelNilaiKuis = new javax.swing.JLabel();
        jTextFieldNilaiKuis = new javax.swing.JTextField();
        jLabelNilaiUTS = new javax.swing.JLabel();
        jTextFieldNilaiUTS = new javax.swing.JTextField();
        jLabelNilaiUAS = new javax.swing.JLabel();
        jTextFieldNilaiUAS = new javax.swing.JTextField();
        jButtonHitung = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jPanelKeterangan = new javax.swing.JPanel();
        jLabelNama1 = new javax.swing.JLabel();
        jTextFieldNama1 = new javax.swing.JTextField();
        jLabelNIM1 = new javax.swing.JLabel();
        jTextFieldNIM1 = new javax.swing.JTextField();
        jLabelRerata = new javax.swing.JLabel();
        jTextFieldRerata = new javax.swing.JTextField();
        jLabelGrade = new javax.swing.JLabel();
        jTextFieldGrade = new javax.swing.JTextField();
        jLabelKeterangan = new javax.swing.JLabel();
        jTextFieldKeterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPesan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInputData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N

        jLabelNama.setText("Nama");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jLabelNIM.setText("NIM");

        jTextFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIMActionPerformed(evt);
            }
        });

        jLabelNilaiTugas.setText("Nilai Tugas");

        jLabelNilaiKuis.setText("Nilai Kuis");

        jLabelNilaiUTS.setText("Nilai UTS");

        jLabelNilaiUAS.setText("Nilai UAS");

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInputDataLayout = new javax.swing.GroupLayout(jPanelInputData);
        jPanelInputData.setLayout(jPanelInputDataLayout);
        jPanelInputDataLayout.setHorizontalGroup(
            jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputDataLayout.createSequentialGroup()
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInputDataLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNama)
                            .addComponent(jLabelNIM)
                            .addComponent(jLabelNilaiTugas)
                            .addComponent(jLabelNilaiKuis)
                            .addComponent(jLabelNilaiUTS)
                            .addComponent(jLabelNilaiUAS))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNama)
                            .addComponent(jTextFieldNIM)
                            .addComponent(jTextFieldNilaiTugas)
                            .addComponent(jTextFieldNilaiKuis)
                            .addComponent(jTextFieldNilaiUTS)
                            .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jPanelInputDataLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonHitung)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimpan)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelInputDataLayout.setVerticalGroup(
            jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNIM)
                    .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNilaiTugas)
                    .addComponent(jTextFieldNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNilaiKuis)
                    .addComponent(jTextFieldNilaiKuis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNilaiUTS)
                    .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNilaiUAS)
                    .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanelInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonSimpan))
                .addGap(23, 23, 23))
        );

        jPanelKeterangan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N

        jLabelNama1.setText("Nama");

        jLabelNIM1.setText("NIM");

        jLabelRerata.setText("Rerata");

        jLabelGrade.setText("Grade");

        jLabelKeterangan.setText("Keterangan");

        jTextAreaPesan.setColumns(20);
        jTextAreaPesan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPesan);

        javax.swing.GroupLayout jPanelKeteranganLayout = new javax.swing.GroupLayout(jPanelKeterangan);
        jPanelKeterangan.setLayout(jPanelKeteranganLayout);
        jPanelKeteranganLayout.setHorizontalGroup(
            jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeteranganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelKeteranganLayout.createSequentialGroup()
                        .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKeterangan)
                            .addComponent(jLabelRerata)
                            .addComponent(jLabelGrade)
                            .addComponent(jLabelNIM1)
                            .addComponent(jLabelNama1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelKeteranganLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextFieldKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldRerata)
                                .addComponent(jTextFieldNama1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNIM1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelKeteranganLayout.setVerticalGroup(
            jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeteranganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama1)
                    .addComponent(jTextFieldNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNIM1)
                    .addComponent(jTextFieldNIM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRerata)
                    .addComponent(jTextFieldRerata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrade)
                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKeterangan)
                    .addComponent(jTextFieldKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInputData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIMActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextAreaPesan.setText("");
        jTextFieldGrade.setText("");
        jTextFieldKeterangan.setText("");
        jTextFieldNIM.setText("");
        jTextFieldNIM1.setText("");
        jTextFieldNama.setText("");
        jTextFieldNama1.setText("");
        jTextFieldNilaiKuis.setText("");
        jTextFieldNilaiTugas.setText("");
        jTextFieldNilaiUAS.setText("");
        jTextFieldNilaiUTS.setText("");
        jTextFieldRerata.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        Simpan();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void validation() {
        try {
            nim = Integer.parseInt(jTextFieldNIM.getText());
        } catch (NumberFormatException ex) {
            jTextAreaPesan.setText("NIM harus berupa angka.");
            jTextFieldNIM.setText("");
        }

        try {
            nilai_tugas = Double.parseDouble(jTextFieldNilaiTugas.getText());
        } catch (NumberFormatException ex) {
            jTextAreaPesan.setText("Nilai Tugas harus berupa angka.");
            jTextFieldNilaiTugas.setText("");
        }

        try {
            nilai_uts = Double.parseDouble(jTextFieldNilaiUTS.getText());
        } catch (NumberFormatException ex) {
            jTextAreaPesan.setText("Nilai UTS harus berupa angka.");
            jTextFieldNilaiUTS.setText("");
        }

        try {
            nilai_uas = Double.parseDouble(jTextFieldNilaiUAS.getText());
        } catch (NumberFormatException ex) {
            jTextAreaPesan.setText("Nilai UAS harus berupa angka.");
            jTextFieldNilaiUAS.setText("");
        }

        try {
            nilai_quiz = Double.parseDouble(jTextFieldNilaiKuis.getText());
        } catch (NumberFormatException ex) {
            jTextAreaPesan.setText("Nilai Quiz harus berupa angka.");
            jTextFieldNilaiKuis.setText("");
        }
    }
    
    private void tampilData() {
        nama = jTextFieldNama.getText();
        jTextFieldNama1.setText(nama);

        nim = Integer.parseInt(jTextFieldNIM.getText());
        jTextFieldNIM1.setText(Integer.toString(nim));

        Hitung();
    }

    private void Hitung() {
        validation();

        rerata = (nilai_tugas + nilai_quiz + nilai_uts + nilai_uas) / 4;
        String rerataString = Double.toString(rerata);
        jTextFieldRerata.setText(rerataString);

        if (rerata >= 90 && rerata <= 100) {
            grade = "A";
            keterangan = "Dinyatakan Lulus";
        } else if (rerata >= 80 && rerata < 90) {
            grade = "B";
            keterangan = "Dinyatakan Lulus";
        } else if (rerata >= 70 && rerata < 80) {
            grade = "C";
            keterangan = "Dinyatakan Mengulang";
        } else {
            grade = "D";
            keterangan = "Dinyatakan Tidak Lulus";
        }
        jTextFieldGrade.setText(grade);
        jTextFieldKeterangan.setText(keterangan);
        jTextAreaPesan.setText("Nilai Berhasil Dihitung");
    }
   
    private boolean Simpan() {
        grade = jTextFieldGrade.getText();
        keterangan = jTextFieldKeterangan.getText();
        nim = Integer.parseInt(jTextFieldNIM.getText());
        nama = jTextFieldNama.getText();
        nilai_quiz = Double.parseDouble(jTextFieldNilaiKuis.getText());
        nilai_tugas = Double.parseDouble(jTextFieldNilaiTugas.getText());
        nilai_uas = Double.parseDouble(jTextFieldNilaiUAS.getText());
        nilai_uts = Double.parseDouble(jTextFieldNilaiUTS.getText());
        rerata = Double.parseDouble(jTextFieldRerata.getText());
        
        try {
            stmt = conn.createStatement();

            // query
            int insert = stmt.executeUpdate("INSERT INTO mahasiswa(`nama`, `nim`, `nilai_tugas`, `nilai_kuis`, `nilai_uts`, `nilai_uas`, `rerata`, `grade`, `keterangan`) "
                    + "VALUES ('" + nama + "'," + nim + "," + nilai_tugas + "," + nilai_quiz + "," + nilai_uts + "," + nilai_uas + "," + rerata + ",'" + grade + "','" + keterangan + "')");

            if (insert == 1) {
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Tersimpan");
                dispose();

                ListData tableDataMahasiswa = new ListData();
                tableDataMahasiswa.setVisible(true);
            }
            return true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error 2: " + ex.getMessage());
        }
        return false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabelGrade;
    private javax.swing.JLabel jLabelKeterangan;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JLabel jLabelNIM1;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNama1;
    private javax.swing.JLabel jLabelNilaiKuis;
    private javax.swing.JLabel jLabelNilaiTugas;
    private javax.swing.JLabel jLabelNilaiUAS;
    private javax.swing.JLabel jLabelNilaiUTS;
    private javax.swing.JLabel jLabelRerata;
    private javax.swing.JPanel jPanelInputData;
    private javax.swing.JPanel jPanelKeterangan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPesan;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldKeterangan;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldNIM1;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNama1;
    private javax.swing.JTextField jTextFieldNilaiKuis;
    private javax.swing.JTextField jTextFieldNilaiTugas;
    private javax.swing.JTextField jTextFieldNilaiUAS;
    private javax.swing.JTextField jTextFieldNilaiUTS;
    private javax.swing.JTextField jTextFieldRerata;
    // End of variables declaration//GEN-END:variables
}
